[world]
name = "0xWindStark"
description = ""
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/0xWindStark"
seed = "windstark"

[world.socials]
x = ""
discord = ""
github = "https://github.com/0xWindStark/backend"
telegram = ""

[namespace]
default = "windstark"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x04073aa5fc12ea20f83f195d827253914dd99dce6870f8ccb272ca5bc9ca2a83"

[writers]
"windstark" = ["windstark-start_action", "windstark-move_action", "windstark-end_action"]
